// end of the component, outside/closing the loop
              }
        myMail.doDisConnect();
/*
***************************************************************************************************
* $Date: 2021-01-15 12:30:57 +0100 (Fri, 15 Jan 2021) $
* $Revision: 82 $
* $Author: alfred $
* $HeadURL: https://monitoring.slainte.at/svn/slainte/trunk/Talend/EchoMail_Java/GetMail_EndCode.Java $
* $Id: GetMail_EndCode.Java 82 2021-01-15 11:30:57Z alfred $
***************************************************************************************************
*/      
